---
#tasks file for run docker

- name: run docker
  hosts: all
  gather_facts: yes
       
  tasks:
  - name: stop old version
    shell: docker stop some-nginx

  - name: remove old image
    shell: docker rm some-nginx

  - name: pull image 
    shell: docker pull 203.24.50.14:8083/nginx

  - name: run docker 
    shell: docker run --name some-nginx -d -p 8085:80 203.24.50.14:8083/nginx

